### ISSUE TITLE
qa and analysis reports are too heavy - slow loading

### ISSUE THREAD

**Issue by kdaily** [MEP-LINCS/knowledgeportal#12]
They *are* live and available in Synapse, but user experience is not good.

**Comment by markdane** [comment]
@kdaily Can we turn off the preview?

**Comment by kdaily** [comment]
Good question, I don't think so but I'll check to be sure.

**Comment by kdaily** [comment]
We cannot. What we would have to do is to upload new versions of the HTML after I removed you from the special Synapse team that allows for full HTML/Javascript to be rendered.

**Comment by markdane** [comment]
@kdaily What is the next step here and will it help the user experience without me creating lighter versions of these reports?

**Comment by markdane** [comment]
@kdaily This refers to the prior MEMA datasets. The reports I spot checked don't offer a preview so this issue has been resolved and can be closed.

**Comment by kdaily** [comment]
Yup! on our side we instituted a 5MB limit.
