### ISSUE TITLE
where is RNASeq raw data?

### ISSUE THREAD

**Issue by kdaily** [MEP-LINCS/knowledgeportal#37]

**Comment by danielderrick** [comment]
@kdaily Can I go ahead and upload the RNAseq bam files to Synapse?

**Comment by kdaily** [comment]
Checking on where to upload, assigning to myself.

**Comment by kdaily** [comment]
I will create a separate bucket for this and link it to Synapse. I'll let you know when that is completed, hopefully by tomorrow. You'll then be able to use the Synapse client as usual to complete the upload.

**Comment by kdaily** [comment]
Bucket created, you're good to go @danielderrick.

https://www.synapse.org/#!Synapse:syn18496655

**Comment by danielderrick** [comment]
Thanks Kenny! Uploading now

**Comment by danielderrick** [comment]
All are up
