### ISSUE TITLE
this is not a csv

### ISSUE THREAD

**Issue by kdaily** [MEP-LINCS/knowledgeportal#49]
despite it's name, these are not compatible with any normal CSV reader without instructions on what to do with first few rows. Reformat.

https://www.synapse.org/#!Synapse:syn16807732
https://www.synapse.org/#!Synapse:syn16807725

**Comment by markdane** [comment]
These files were created as we explored various normalizations. We can delete them and close this issue.

**Comment by markdane** [comment]
Older files moved to archive
