### ISSUE TITLE
document purpose for each report type

### ISSUE THREAD

**Issue by kdaily** [MEP-LINCS/knowledgeportal#9]
could go on release wiki (https://www.synapse.org/#!Synapse:syn2862345/wiki/394513), or elsewhere

**Comment by markdane** [comment]
Added:
Every data set has two QA reports and one analysis report. The QA_Cell reports include cell-level histograms and dot plots used to evaluate the Immunofluorescent staining, image segmentation and and intensity quantification. The QA_SpotMEP reports evaluate the assay results at the spot and MEP summarized levels. The Analysis reports provide interactive tools that use unbiased or biologically-driven methods to identify perturbations of interest.
